name: Make and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make Assembly
      run: make Assembly
    - name: run Assembler prog1.asm
      run: ./bin/Assembler sample_data/prog1.asm
    - name: make ConvertAssembly
      run: make ConvertAssembly
    - name: run ConvertAssembly prog1.asm
      run: ./bin/ConvertAssembly output/prog1bin.txt
    - name: make clean
      run: make clean
      
